name: HACS Action
# see: https://github.com/hacs/action refered by https://hacs.xyz/docs/publish/include#before-submitting

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  hacs:
    name: HACS Action
    runs-on: "ubuntu-latest"
    steps:
      - name: HACS Action
        uses: "hacs/action@main"
        with:
          category: "integration"
